input_path: 'input/freshtomato-RT-AC3200-ARM-2022.5-AIO-64K.zip'
tmp_dir: 'tmp'
report_dir: 'report'
log_dir: 'log'

debug_mode: True
preprocess_timeout: 120

checkers:
  ConstantKeysChecker:
    enable: True
    desc: 'Do not use constant encryption keys'
    criteria:
      crypt:
        lib_from: 'crypt'
        arg_index: 0
  ConstantSaltsChecker:
    enable: True
    desc: 'Do not use constant salts for password-based encryption (PBE)'
    criteria:
      crypt:
        lib_from: 'crypt'
        arg_index: 1